# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-05 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaveEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NewEmail', models.EmailField(help_text=b'A valid email address, please.', max_length=254)),
            ],
        ),
    ]
