# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-05 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SaveEmail',
            new_name='email',
        ),
    ]
