# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-05 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20190205_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='NewEmail',
        ),
        migrations.AddField(
            model_name='email',
            name='email',
            field=models.EmailField(default=b'votre email', help_text=b'Entrer une adresse email valide <br>', max_length=254),
        ),
    ]
